language: python
dist: xenial
python:
- 3.6
- 3.7
install:
- pip install pipenv flake8 tox-travis
- pipenv install
script:
- pipenv run flake8
- pipenv run tox
deploy:
  provider: pypi
  user: sobamchan
  on:
    tags: true
  skip_existing: true
  password:
    secure: cB2aZ5deU/tUZr57quD6K+OGEWORKTDf84Ia75261OQcKhBtO1c37mQH73vTaory6dRGyggdlz5ktP8x4ad5fqUXMhhe2PoBoveIyGrQB0Tk4U2fqaEpuwMdcVd7IR3kMehVJ1v+nvf3vetUWgnnM84emjH6tCvb9E1kmcn+BhMTeDSUqNYivJiQYWmT/1ToontpXRynygqBjN3xcjTcFUUQR9jZ72NkSgxjFs2oGQDLwdPWEghPzOEkNXPsUO3OoyTMDUF3z51yTsGMP4Sts67QKvW9W/zUexsweZZTQTu64fcsdE6YE2EsNuAtGZ3fjltV7MbZ9nGrx7AXjlVns4hICh67exPJMw8YoQHzJV0VBy20Gg3y6TKntxCSige4RnTQvIYG6c6nK3D2W9FLruLkwEmQRHz9fsCQ1PR5AsFRYJ0n5FZh+Gi1NqfXAMfl84MSklNXgA0H4rkzjVdrrQz/il4Ky0QAKzUfogSlA7D/XIgyGV+UQ2IsylLZ2DSAgG3V+ng/MY+c93vKD9OKM5oOpqPlGHLVXOOS8Mhx89BeGwPhp7zxw54qqbQK+2PSWSxHUzD/h4cYfsRH4CNV2UFtrXXNQsabRyDjDdYTjjn4fYMWBIrcTCtMsQBQXgQ9Wy9QOM9qeW6jObrT0aPvTfPxSzBykiYjjKvxFkWmTVQ=
